# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/django-2.1.2-python_3.6-on-linux_64, last modified Sat Oct 13 21:08:46 2018
# ------------------------------------------------

package:
    name: django
    version: 2.1.2
source:
    sha256: efbcad7ebb47daafbcead109b38a5bd519a3c3cd92c6ed0f691ff97fcdd16b45
    url: https://pypi.io/packages/source/D/Django/Django-2.1.2.tar.gz
build:
    entry_points:
        - django-admin = django.core.management:execute_from_command_line
    noarch: false
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py36_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.8.24 py36_1
        - libedit 3.1.20170329 h6b74fdf_2
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - ncurses 6.1 hf484d3e_0
        - openssl 1.0.2p h14c3975_0
        - python 3.6.6 h6e4f718_2
        - readline 7.0 h7b6447c_5
        - setuptools 40.4.3 py36_0
        - sqlite 3.25.2 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 ha838bed_2
    run:
        - python >=3.6,<3.7.0a0
        - pytz
test:
    commands:
        - django-admin --help
    imports:
        - django
        - django.apps
        - django.conf
        - django.conf.app_template.migrations
        - django.conf.locale
        - django.conf.locale.ar
        - django.conf.locale.az
        - django.conf.locale.bg
        - django.conf.locale.bn
        - django.conf.locale.bs
        - django.conf.locale.ca
        - django.conf.locale.cs
        - django.conf.locale.cy
        - django.conf.locale.da
        - django.conf.locale.de
        - django.conf.locale.de_CH
        - django.conf.locale.el
        - django.conf.locale.en
        - django.conf.locale.en_AU
        - django.conf.locale.en_GB
        - django.conf.locale.eo
        - django.conf.locale.es
        - django.conf.locale.es_AR
        - django.conf.locale.es_CO
        - django.conf.locale.es_MX
        - django.conf.locale.es_NI
        - django.conf.locale.es_PR
        - django.conf.locale.et
        - django.conf.locale.eu
        - django.conf.locale.fa
        - django.conf.locale.fi
        - django.conf.locale.fr
        - django.conf.locale.fy
        - django.conf.locale.ga
        - django.conf.locale.gd
        - django.conf.locale.gl
        - django.conf.locale.he
        - django.conf.locale.hi
        - django.conf.locale.hr
        - django.conf.locale.hu
        - django.conf.locale.id
        - django.conf.locale.it
        - django.conf.locale.ja
        - django.conf.locale.ka
        - django.conf.locale.km
        - django.conf.locale.kn
        - django.conf.locale.ko
        - django.conf.locale.lt
        - django.conf.locale.lv
        - django.conf.locale.mk
        - django.conf.locale.ml
        - django.conf.locale.mn
        - django.conf.locale.nb
        - django.conf.locale.nl
        - django.conf.locale.nn
        - django.conf.locale.pl
        - django.conf.locale.pt
        - django.conf.locale.pt_BR
        - django.conf.locale.ro
        - django.conf.locale.ru
        - django.conf.locale.sk
        - django.conf.locale.sl
        - django.conf.locale.sq
        - django.conf.locale.sr
        - django.conf.locale.sr_Latn
        - django.conf.locale.sv
        - django.conf.locale.ta
        - django.conf.locale.te
        - django.conf.locale.th
        - django.conf.locale.tr
        - django.conf.locale.uk
        - django.conf.locale.vi
        - django.conf.locale.zh_Hans
        - django.conf.locale.zh_Hant
        - django.conf.urls
        - django.contrib
        - django.contrib.admin
        - django.contrib.admin.migrations
        - django.contrib.admin.templatetags
        - django.contrib.admin.views
        - django.contrib.admindocs
        - django.contrib.auth
        - django.contrib.auth.handlers
        - django.contrib.auth.management
        - django.contrib.auth.management.commands
        - django.contrib.auth.migrations
        - django.contrib.contenttypes
        - django.contrib.contenttypes.management
        - django.contrib.contenttypes.management.commands
        - django.contrib.contenttypes.migrations
        - django.contrib.flatpages
        - django.contrib.flatpages.migrations
        - django.contrib.flatpages.templatetags
        - django.contrib.gis
        - django.contrib.gis.db
        - django.contrib.gis.db.backends
        - django.contrib.gis.db.backends.base
        - django.contrib.gis.db.backends.mysql
        - django.contrib.gis.db.backends.oracle
        - django.contrib.gis.db.backends.postgis
        - django.contrib.gis.db.backends.spatialite
        - django.contrib.gis.geometry
        - django.contrib.gis.management
        - django.contrib.gis.management.commands
        - django.contrib.gis.serializers
        - django.contrib.humanize
        - django.contrib.humanize.templatetags
        - django.contrib.messages
        - django.contrib.messages.storage
        - django.contrib.postgres
        - django.contrib.postgres.forms
        - django.contrib.redirects
        - django.contrib.redirects.migrations
        - django.contrib.sessions
        - django.contrib.sessions.backends
        - django.contrib.sessions.management
        - django.contrib.sessions.management.commands
        - django.contrib.sessions.migrations
        - django.contrib.sitemaps
        - django.contrib.sitemaps.management
        - django.contrib.sitemaps.management.commands
        - django.contrib.sites
        - django.contrib.sites.migrations
        - django.contrib.staticfiles
        - django.contrib.staticfiles.management
        - django.contrib.staticfiles.management.commands
        - django.contrib.staticfiles.templatetags
        - django.contrib.syndication
        - django.core
        - django.core.cache
        - django.core.cache.backends
        - django.core.checks
        - django.core.checks.compatibility
        - django.core.checks.security
        - django.core.files
        - django.core.handlers
        - django.core.mail
        - django.core.mail.backends
        - django.core.management
        - django.core.management.commands
        - django.core.serializers
        - django.core.servers
        - django.db
        - django.db.backends
        - django.db.backends.base
        - django.db.backends.dummy
        - django.db.backends.mysql
        - django.db.backends.oracle
        - django.db.backends.postgresql
        - django.db.backends.postgresql_psycopg2
        - django.db.backends.sqlite3
        - django.db.migrations
        - django.db.migrations.operations
        - django.db.models
        - django.db.models.fields
        - django.db.models.functions
        - django.db.models.sql
        - django.dispatch
        - django.forms
        - django.http
        - django.middleware
        - django.template
        - django.template.backends
        - django.template.loaders
        - django.templatetags
        - django.test
        - django.urls
        - django.utils
        - django.utils.translation
        - django.views
        - django.views.decorators
        - django.views.generic
    requires:
        - psycopg2
about:
    dev_url: https://github.com/django/django
    doc_url: http://www.djangoproject.com/
    home: http://www.djangoproject.com/
    license: BSD 3-Clause
    license_file: LICENSE
    summary: A high-level Python Web framework that encourages rapid development and
        clean, pragmatic design.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - kwilcox
        - ocefpaf
